name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby 2.4/stable
      run: |
        sudo snap switch ruby --channel=2.4/stable
        sudo snap refresh
        sudo snap install ruby --classic
    - name: Test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake test
